function generateReferencePF(problemHandles, M, targetN, problemNames)
%GENERATEREFERENCEPF Generate and store reference Pareto fronts for given problems.
%
%   generateReferencePF(problemHandles, M, targetN)
%   generateReferencePF(problemHandles, M, targetN, problemNames)
%
%   For each problem, generates ~targetN discrete points on the true Pareto
%   front and saves them to ./Info/ReferencePF/RefPF-{ProblemName}.mat.
%
%   Three classes of problems are handled differently:
%     Class 1 (most problems): GetOptimum(N) works but may not return
%       exactly N points. Binary search finds N that yields ~targetN points.
%     Class 2 (pre-computed PFs): The true PF is approximated and stored
%       in .mat files. Points are extracted uniformly while preserving corners.
%     Combinatorial (MOTSP, MOKP): Approximate PFs generated by running
%       multiple MOEAs (see generateApproximatePF).  Treated as Class 2
%       once the .mat file exists.
%
%   Input:
%     problemHandles - Cell array of problem function handles
%     M              - Number of objectives. Scalar (applied to all) or
%                      vector with one value per problem. (default: 3)
%     targetN        - Target number of PF points (default: 1000)
%     problemNames   - (optional) Cell array of unique pipeline names.
%                      Defaults to func2str of each handle.
%                      For combinatorial: use pipeline names (e.g. 'MOTSP_ID1')

    if nargin < 2 || isempty(M)
        M = 3;
    end
    if nargin < 3 || isempty(targetN)
        targetN = 1000;
    end

    % Expand scalar M to vector
    if isscalar(M)
        M = repmat(M, 1, numel(problemHandles));
    end

    % Default pipeline names = raw class names
    if nargin < 4 || isempty(problemNames)
        problemNames = cellfun(@func2str, problemHandles, 'UniformOutput', false);
    end

    % Class 2 problems: PF approximated by MOEA, stored in .mat files
    class2Names = {'WFG3', 'MinusDTLZ5', 'MinusDTLZ6', 'MinusWFG2', 'MinusWFG3', ...
        'RWA1', 'RWA2', 'RWA3', 'RWA4', 'RWA5', 'RWA6', 'RWA7', 'RWA8', 'RWA9', 'RWA10'};

    % Combinatorial problems: approximate PF via generateApproximatePF
    combiNames = {'MOTSP', 'MOKP'};

    % Ensure output directory exists
    outputDir = './Info/ReferencePF';
    if ~exist(outputDir, 'dir')
        mkdir(outputDir);
    end

    numProblems = numel(problemHandles);
    fprintf('=== Generating Reference Pareto Fronts ===\n');
    fprintf('Target: ~%d points per problem\n\n', targetN);

    for i = 1:numProblems
        ph = problemHandles{i};
        rawName = func2str(ph);      % Class name: 'MOTSP'
        pipeName = problemNames{i};   % Pipeline name: 'MOTSP_ID1'
        M_i = M(i);

        fprintf('[%d/%d] %s (M=%d): ', i, numProblems, pipeName, M_i);

        if ismember(rawName, combiNames)
            % Combinatorial: generateApproximatePF saves directly to ReferencePF
            refPath = fullfile(outputDir, sprintf('RefPF-%s.mat', pipeName));
            if exist(refPath, 'file')
                fprintf('already exists (from generateApproximatePF), skipping.\n');
            else
                fprintf('WARNING - RefPF not found. Run generateApproximatePF(%s, %d, D, %s) first.\n', ...
                    rawName, M_i, extractAfter(pipeName, '_ID'));
            end
            continue;
        elseif ismember(rawName, class2Names)
            % Class 2: load from pre-computed .mat file
            PF = generateClass2PF(rawName, targetN);
        else
            % Class 1: binary search with GetOptimum
            Problem = ph('M', M_i);
            PF = generateClass1PF(Problem, targetN);
        end

        if isempty(PF)
            fprintf('WARNING - empty PF, skipping.\n');
            continue;
        end

        % Filter to non-dominated only
        frontRank = NDSort(PF, 1);
        PF = PF(frontRank == 1, :);

        % Save using pipeline name (e.g. RefPF-MOTSP_ID1.mat)
        outPath = fullfile(outputDir, sprintf('RefPF-%s.mat', pipeName));
        save(outPath, 'PF');
        fprintf('%d points saved to %s\n', size(PF, 1), outPath);
    end

    fprintf('\n=== Reference PF generation complete ===\n');
end

%% ==================== CLASS 1: Binary Search ====================

function PF = generateClass1PF(Problem, targetN)
%GENERATECLASS1PF Use binary search to find N that yields ~targetN points.

    % Step 1: Probe to find a range [lo, hi] where lo yields < targetN
    % and hi yields >= targetN
    step = 500;
    lo = targetN;
    PF_lo = Problem.GetOptimum(lo);
    count_lo = size(PF_lo, 1);

    if count_lo >= targetN
        % Already have enough (or more) at N=targetN
        % Try to find exact match or downsample
        PF = downsampleIfNeeded(PF_lo, targetN);
        return;
    end

    % Step upward until we find enough
    hi = lo + step;
    maxAttempts = 20;
    for attempt = 1:maxAttempts
        PF_hi = Problem.GetOptimum(hi);
        count_hi = size(PF_hi, 1);

        if count_hi >= targetN
            break;
        end

        lo = hi;
        count_lo = count_hi;
        PF_lo = PF_hi;

        % Increase step size if 500 isn't working
        if attempt >= 5
            step = 1000;
        end
        hi = hi + step;
    end

    if count_hi < targetN
        % Could not find enough points even after many attempts
        fprintf('(max %d pts at N=%d) ', count_hi, hi);
        PF = PF_hi;
        return;
    end

    % Step 2: Binary search between [lo, hi]
    tolerance = 5;  % Accept within +/- 5 of targetN
    bestPF = PF_hi;
    bestDiff = abs(count_hi - targetN);

    for iter = 1:15
        if hi - lo <= 1
            break;
        end

        mid = round((lo + hi) / 2);
        PF_mid = Problem.GetOptimum(mid);
        count_mid = size(PF_mid, 1);

        diff = abs(count_mid - targetN);
        if diff < bestDiff
            bestDiff = diff;
            bestPF = PF_mid;
        end

        if count_mid == targetN || diff <= tolerance
            break;
        elseif count_mid < targetN
            lo = mid;
        else
            hi = mid;
        end
    end

    PF = downsampleIfNeeded(bestPF, targetN);
end

function PF = downsampleIfNeeded(PF, targetN)
    return
end
% function PF = downsampleIfNeeded(PF, targetN)
% %DOWNSAMPLEIFNEEDED Downsample PF to targetN if it has more points.
%     if size(PF, 1) > targetN
%         [idx, ~] = getLeastCrowdedPoints(PF, targetN);
%         PF = PF(idx, :);
%     end
% end

%% ==================== CLASS 2: Extract from .mat ====================

function PF = generateClass2PF(problemName, targetN)
%GENERATECLASS2PF Extract ~targetN uniformly distributed points from stored .mat file.

    % Determine benchmark suite and locate .mat file
    matPath = locateMatFile(problemName);

    if isempty(matPath) || ~exist(matPath, 'file')
        fprintf('WARNING - .mat file not found for %s. ', problemName);
        PF = [];
        return;
    end

    % Load PF data (handle different variable names)
    data = load(matPath);
    if isfield(data, 'F')
        rawPF = data.F;
    elseif isfield(data, 'PF')
        rawPF = data.PF;
    else
        % Try first field
        fields = fieldnames(data);
        if ~isempty(fields)
            rawPF = data.(fields{1});
        else
            fprintf('WARNING - no data in %s. ', matPath);
            PF = [];
            return;
        end
    end

    fprintf('(loaded %d raw points) ', size(rawPF, 1));

    if size(rawPF, 1) <= targetN
        PF = rawPF;
        return;
    end

    % Identify corner solutions (min on each objective)
    M = size(rawPF, 2);
    cornerIdx = zeros(M, 1);
    for j = 1:M
        [~, cornerIdx(j)] = min(rawPF(:, j));
    end
    cornerIdx = unique(cornerIdx);
    numCorners = numel(cornerIdx);

    % Separate corners from candidates
    allIdx = (1:size(rawPF, 1))';
    candidateIdx = setdiff(allIdx, cornerIdx);
    candidates = rawPF(candidateIdx, :);

    % Select remaining points uniformly
    numToSelect = targetN - numCorners;
    if numToSelect > 0 && size(candidates, 1) > numToSelect
        [selectedSubIdx, ~] = getLeastCrowdedPoints(candidates, numToSelect);
        selectedIdx = candidateIdx(selectedSubIdx);
    elseif numToSelect > 0
        selectedIdx = candidateIdx;
    else
        selectedIdx = [];
    end

    % Combine corners + selected
    finalIdx = [cornerIdx; selectedIdx];
    PF = rawPF(finalIdx, :);
end

function matPath = locateMatFile(problemName)
%LOCATEMATFILE Find the .mat file for a given problem name.
    baseDir = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    probDir = fullfile(baseDir, 'Problems', 'Multi-objective optimization');

    % Map problem names to benchmark suite directories
    % Note: MOTSP/MOKP are handled directly by generateApproximatePF
    % and no longer route through locateMatFile.
    if startsWith(problemName, 'MinusWFG')
        suite = 'MinusWFG';
    elseif startsWith(problemName, 'MinusDTLZ')
        suite = 'MinusDTLZ';
    elseif startsWith(problemName, 'WFG')
        suite = 'WFG';
    elseif startsWith(problemName, 'RWA')
        suite = 'RWA';
    else
        suite = problemName;
    end

    matPath = fullfile(probDir, suite, [problemName '.mat']);
end
